
[deps.openssl]
version = "<=julia"

[deps.libstdcxx]
version = "<=julia"

[deps.libstdcxx-ng]
version = "<=julia"

[deps.python]
build = "**cpython**"
version = ">=3.10,!=3.14.0,!=3.14.1,<4"

[dev.deps]
matplotlib = ""
numpy = ""
pyside6 = ""
