
[deps.openssl]
version = "<=julia"

[deps.libstdcxx]
version = "<=julia"

[deps.libstdcxx-ng]
version = "<=julia"

[deps.python]
build = "**cpython**"
version = ">=3.10,<4"

[dev.deps]
matplotlib = ""
numpy = ""
pyside6 = ""
python = "<3.14"
