name: 'Stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:
permissions:
  issues: write
  pull-requests: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          exempt-all-milestones: true
          exempt-issue-labels: priority,help wanted,no stale
          days-before-issue-stale: 30
          stale-issue-message: >
            Thank you for taking the time to report this issue!

            However, it has been marked as stale because there has been no activity for 30
            days. As with many open source projects, the maintainers work for free and do
            not always have enough time to address all issues.

            For questions, please check the documentation, other issues, or consider asking
            elsewhere such as Stack Overflow or Julia Discourse. For bugs, please try to
            find a fix yourself and consider opening a pull request. If you're still stuck,
            please leave a comment below.

            If there is no further activity in 7 days, this issue will be automatically
            closed.
          exempt-pr-labels: priority,help wanted,no stale
          days-before-pr-stale: 180
          stale-pr-message: >
            Thank you for taking the time to create this pull request!

            However, it has been marked as stale because there has been no activity for 6
            months. As with many open source projects, the maintainers work for free and do
            not always have enough time to review all PRs.

            Please ensure that all tests are passing, and that any new functionality has
            corresponding new tests (which should fail on old code and pass on new code).
            Also ensure any changes are documented or commented appropriately. If you're
            sure the PR is ready for review, please leave a comment below.

            If there is no further activity in 30 days, this issue will be automatically
            closed.
          days-before-issue-close: 7
          close-issue-message: >
            This issue has been closed because it has been stale for 7 days. If it is still
            relevant, please re-open it.
          days-before-pr-close: 30
          close-pr-message: >
            This PR has been closed because it has been stale for 30 days. If it is still
            relevant, please re-open it.
